// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./components/Provider/AppProvider.vue')['default'];
    HelloWorld: typeof import('./components/HelloWorld.vue')['default'];
    NButton: typeof import('naive-ui')['NButton'];
    NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
    NDialogProvider: typeof import('naive-ui')['NDialogProvider'];
    NDrawer: typeof import('naive-ui')['NDrawer'];
    NDrawerContent: typeof import('naive-ui')['NDrawerContent'];
    NIcon: typeof import('naive-ui')['NIcon'];
    NLayout: typeof import('naive-ui')['NLayout'];
    NLayoutContent: typeof import('naive-ui')['NLayoutContent'];
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter'];
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader'];
    NLayoutSider: typeof import('naive-ui')['NLayoutSider'];
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider'];
    NMessageProvider: typeof import('naive-ui')['NMessageProvider'];
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider'];
    NSpace: typeof import('naive-ui')['NSpace'];
    Setting: typeof import('./components/Setting/Setting.vue')['default'];
  }
}

export {};
